#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SuperLig")]
	public partial class SuperligTakımDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTakımlar(Takımlar instance);
    partial void UpdateTakımlar(Takımlar instance);
    partial void DeleteTakımlar(Takımlar instance);
    #endregion
		
		public SuperligTakımDataContext() : 
				base(global::WindowsFormsApp3.Properties.Settings.Default.SuperLigConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SuperligTakımDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SuperligTakımDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SuperligTakımDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SuperligTakımDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Takımlar> Takımlar
		{
			get
			{
				return this.GetTable<Takımlar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Takımlar")]
	public partial class Takımlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Takım_Id;
		
		private string _Takım_Name;
		
		private System.Nullable<int> _Oyun;
		
		private System.Nullable<int> _Galibiyet;
		
		private System.Nullable<int> _Puan;
		
		private System.Data.Linq.Binary _Logo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTakım_IdChanging(int value);
    partial void OnTakım_IdChanged();
    partial void OnTakım_NameChanging(string value);
    partial void OnTakım_NameChanged();
    partial void OnOyunChanging(System.Nullable<int> value);
    partial void OnOyunChanged();
    partial void OnGalibiyetChanging(System.Nullable<int> value);
    partial void OnGalibiyetChanged();
    partial void OnPuanChanging(System.Nullable<int> value);
    partial void OnPuanChanged();
    partial void OnLogoChanging(System.Data.Linq.Binary value);
    partial void OnLogoChanged();
    #endregion
		
		public Takımlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takım_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Takım_Id
		{
			get
			{
				return this._Takım_Id;
			}
			set
			{
				if ((this._Takım_Id != value))
				{
					this.OnTakım_IdChanging(value);
					this.SendPropertyChanging();
					this._Takım_Id = value;
					this.SendPropertyChanged("Takım_Id");
					this.OnTakım_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takım_Name", DbType="NVarChar(MAX)")]
		public string Takım_Name
		{
			get
			{
				return this._Takım_Name;
			}
			set
			{
				if ((this._Takım_Name != value))
				{
					this.OnTakım_NameChanging(value);
					this.SendPropertyChanging();
					this._Takım_Name = value;
					this.SendPropertyChanged("Takım_Name");
					this.OnTakım_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oyun", DbType="Int")]
		public System.Nullable<int> Oyun
		{
			get
			{
				return this._Oyun;
			}
			set
			{
				if ((this._Oyun != value))
				{
					this.OnOyunChanging(value);
					this.SendPropertyChanging();
					this._Oyun = value;
					this.SendPropertyChanged("Oyun");
					this.OnOyunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Galibiyet", DbType="Int")]
		public System.Nullable<int> Galibiyet
		{
			get
			{
				return this._Galibiyet;
			}
			set
			{
				if ((this._Galibiyet != value))
				{
					this.OnGalibiyetChanging(value);
					this.SendPropertyChanging();
					this._Galibiyet = value;
					this.SendPropertyChanged("Galibiyet");
					this.OnGalibiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Int")]
		public System.Nullable<int> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this.OnPuanChanging(value);
					this.SendPropertyChanging();
					this._Puan = value;
					this.SendPropertyChanged("Puan");
					this.OnPuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
